edge case if config key is empty

diff --git a/build/switcherTest b/build/switcherTest
--- a/build/switcherTest
+++ b/build/switcherTest
@@ -10,13 +10,19 @@ testFile="../../secrets/secretsRegexTestFile"
 resultsFile="${testFile}Result"
 
 function runATest {
+	configKey="$1"
 	replacePHPConfig "$configKey" "$testValue" "$resultsFile"
-	testResult=$( { cat $resultsFile && echo "<?php echo $testValue ?>" ;}  | php )
-	if [[ $testResult == $testValue ]]; then
-		echo "Success - test result is $testResult"
+	if (($?==1)); then	
+		echo "Test failed - config key was empty"
+		((failedTests++))
 	else
-		echo "Failiure - test result is $testResult"
-		((failedTests++))	
+		testResult=$( { cat $resultsFile && echo "<?php echo $testValue ?>" ;}  | php )
+		if [[ $testResult == $testValue ]]; then
+			echo "Success - "$configKey" result is $testResult"
+		else 
+			echo "Failiure - "$configKey" test result is $testResult"
+			((failedTests++))
+		fi
 	fi
 }
 
@@ -31,12 +37,11 @@ fi
 
 # Run tests
 echo "Test Batch 1 - replace AdminSettings.php"
-configKey="$wgDBadminpassword" 
-runATest
+runATest '$wgDBadminpassword' 
 
 # After
-if (( $failedTests > 1 )); then 
-	echo "Problems found, investigate"
+if (( failedTests > 0 )); then 
+	echo "Problems found - number of failed tests is $failedTests, investigate"
 else
 	echo "All tests seemed to pass"
 fi
